### ISSUE TITLE
`DropTarget` panics when calling the `"drop"` signal handler

### ISSUE THREAD

**Issue by DeedleFake** [diamondburned/gotk4#107]
Code:

https://github.com/DeedleFake/trayscale/blob/561c7bd0a94cb11b92353b91125e023815882020/cmd/trayscale/app.go#L541-L545

```go
page.container.AddController(page.container.DropTarget)
page.container.DropTarget.SetGTypes([]glib.Type{gio.GTypeFile})
page.container.DropTarget.ConnectDrop(func(val glib.Value, x, y float64) bool {
	return true
})
```

Result:

```
panic: given unknown closure user_data

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/gtk/v4._gotk4_gtk4_DropTarget_ConnectDrop(0x99e9e0?, {0x806, {{0x70, 0xf7, 0xe3, 0x7c, 0xfc, 0x7f, 0x0, 0x0}, ...}}, ...)
        $GOPATH/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.5/gtk/v4/gtkdroptarget_export.go:67 +0x14f
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x4406850, 0x1, 0x44f2860)
        _cgo_gotypes.go:13957 +0x4c
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0xc00048cbf0?, 0x29?, 0x44f2860?)
        $GOPATH/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.5/gio/v2/gapplication_2_28.go:1266 +0x71
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc0002a4018, {0xc000118250?, 0x1, 0x1})
        $GOPATH/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.5/gio/v2/gapplication_2_28.go:1266 +0x1e5
main.(*App).Run(0xc00029a000, {0x1b3fb60?, 0xc000158400?})
        $MODROOT/cmd/trayscale/app.go:450 +0x292
main.main()
        $MODROOT/cmd/trayscale/trayscale.go:130 +0x128
exit status 2
```

**Comment by diamondburned** [comment]
I'm not too sure why this happens. Perhaps the objects aren't being freed in order? It's really hard for me to tell.

Does adding `runtime.KeepAlive(page.container.DropTarget)` into the closure work?

**Comment by DeedleFake** [comment]
No change. It's not going to get freed first anyways, though, because a reference to `page` is retained elsewhere.

**Comment by diamondburned** [comment]
So `AddController` doesn't seem to take its own reference (transfer: full); perhaps you need to call `.Ref()` on it? Otherwise, the reference is considered to be Go's and is dropped whenever. Maybe the generator should generate something about this.

**Comment by DeedleFake** [comment]
I'm not sure what you want me to try calling `Ref()` on. The Go references to all of those objects are retained well past the triggering of the `"drop"` signal, so I don't think that that should be an issue.

**Comment by micaplush** [comment]
In case anyone stumbles across this, I've experienced the same error and had success replacing

```go
dt.ConnectDrop(func(value glib.Value, x, y float64) (ok bool) {
	// handler code...
})
```

with

```go
dt.Connect("drop", func(value *glib.Value, x, y float64) (ok bool) {
	// handler code...
})
```

**Comment by diamondburned** [comment]
That's strange, I'm not sure why this would work and `ConnectDrop` wouldn't. Perhaps it has to do with the `glib.Value` argument (that should be a pointer instead)?

**Comment by DeedleFake** [comment]
It gives a different error when using `"drop"` manually with a `glib.Value` than it does with `ConnectDrop()`, though:

```
panic: reflect.Value.Convert: value of type *glib.Value cannot be converted to type glib.Value [recovered]
        panic: closure error: unexpected panic caught: reflect.Value.Convert: value of type *glib.Value cannot be converted to type glib.Value
```

**Comment by DeedleFake** [comment]
After some testing, it seems like while manually using `"drop"` _does_ work, about 10% of the time or so it segfaults.

**Comment by micaplush** [comment]
That's strange. The `Connect("drop", ...)` workaround works fine for me.

Here's some code I used to try it:

```go
package main

import (
	"fmt"
	"os"

	"github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gdk/v4"
	"github.com/diamondburned/gotk4/pkg/gio/v2"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

func main() {
	app := gtk.NewApplication("com.example.dnd", gio.ApplicationFlagsNone)

	app.ConnectActivate(func() {
		activate(app)
	})

	app.Run(os.Args)
}

func activate(app *gtk.Application) {
	win := gtk.NewApplicationWindow(app)
	win.SetApplication(app)
	win.SetDefaultSize(1280, 720)
	
	b := gtk.NewBox(gtk.OrientationVertical, 0)
	win.SetChild(b)

	btn1 := gtk.NewButtonWithLabel("Source")
	ds := gtk.NewDragSource()
	ds.ConnectPrepare(func(x, y float64) (contentProvider *gdk.ContentProvider) {
		return gdk.NewContentProviderForValue(glib.NewValue("hello dnd"))
	})
	btn1.AddController(ds)
	b.Append(btn1)

	btn2 := gtk.NewButtonWithLabel("Target")
	dt := gtk.NewDropTarget(glib.TypeString, gdk.ActionCopy)
	dt.Connect("drop", func(value *glib.Value, x, y float64) (ok bool) {
		fmt.Println(value.String())
		return true
	})
	btn2.AddController(dt)
	b.Append(btn2)

	win.Show()
}
```

It seems to work with both the app-internal drag source and for dragging files from Nautilus. If it helps, I used the following Nix shell for compiling:

```nix
with (import <nixpkgs> { }); # version: 23.05.2533.9652a97d9738 (Stoat)

mkShell {
  packages = [
    delve
    go_1_20

    pkg-config
    glib
    gobject-introspection
    cairo
    graphene
    pango
    gdk-pixbuf
    gtk4
    atk
    dbus
  ];
}
```

**Comment by diamondburned** [comment]
This issue has been fixed in the code generator.
