### ISSUE TITLE
Simple program crashed: BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by nekohasekai** [diamondburned/gotk4#32]
Source:

go.mod
```
require github.com/diamondburned/gotk4/pkg v0.0.0-20210822212111-9ca8639aeefb
```

main.go
```golang
package main

import (
	"github.com/diamondburned/gotk4/pkg/gio/v2"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
	"os"
)

func main() {
	app := gtk.NewApplication("com.example.myapplication", gio.ApplicationFlagsNone)
	app.Connect("activate", activate)

	os.Exit(app.Run(os.Args))
}

func activate(app *gtk.Application) {
	w := gtk.NewApplicationWindow(app)
	h := gtk.NewHeaderBar()
	h.SetShowTitleButtons(true)
	w.SetTitlebar(h)
	w.SetTitle("test")
	w.SetDefaultSize(800, 500)
	w.Show()
}

```

After drag/resize:
```
$ go run -v main.go
command-line-arguments

(main:198791): Gtk-WARNING **: 20:06:51.374: Unknown key gtk-button-images in /home/sekai/.config/gtk-4.0/settings.ini

(main:198791): Gtk-WARNING **: 20:06:51.374: Unknown key gtk-menu-images in /home/sekai/.config/gtk-4.0/settings.ini

(main:198791): Gtk-WARNING **: 20:06:51.374: Unknown key gtk-toolbar-style in /home/sekai/.config/gtk-4.0/settings.ini

(main:198791): Gdk-CRITICAL **: 20:06:58.136: gdk_surface_request_layout: assertion 'frame_clock' failed

(main:198791): Gdk-ERROR **: 20:06:58.137: The program 'main' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 4344 error_code 3 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
SIGTRAP: trace trap
PC=0x7fe6ad5400f8 m=0 sigcode=128

goroutine 0 [idle]:
runtime: unknown pc 0x7fe6ad5400f8
stack: frame={sp:0x7ffc8f5296d0, fp:0x0} stack=[0x7ffc8ed2ba10,0x7ffc8f52aa50)
0x00007ffc8f5295d0:  0x00007ffc8f5295e0  0x53e30870fee58e00 
0x00007ffc8f5295e0:  0x00000000029c9d2d  0x00000000029c9c00 
0x00007ffc8f5295f0:  0x00000000029c9c00  0x0000000003a36340 
0x00007ffc8f529600:  0x0000000000000001  0x0000000000000001 
0x00007ffc8f529610:  0x010004157f1c0300  0x170f12001a131100 
0x00007ffc8f529620:  0x0000000000000016  0x53e30870fee58e00 
0x00007ffc8f529630:  0x0000000000000000  0xffffffffffffff80 
0x00007ffc8f529640:  0x000000000000000b  0x0000000000000006 
0x00007ffc8f529650:  0x00007fe6aca34440  0x0000000000000006 
0x00007ffc8f529660:  0x00007fe6ad614d50  0x00007fe6ac8fe9e8 
0x00007ffc8f529670:  0x00007fe6aca35300  0x00007fe6ac8e7ba6 
0x00007ffc8f529680:  0x00007fe6aca34440  0x0000000000000006 
0x00007ffc8f529690:  0x0000000003a36340  0x00007fe6ad53febc 
0x00007ffc8f5296a0:  0x0000000000000044  0x00007ffc8f529770 
0x00007ffc8f5296b0:  0x0000000000000006  0x0000000000000000 
0x00007ffc8f5296c0:  0x00007fe6ad614ce0  0x00007fe6ad5400eb 
0x00007ffc8f5296d0: <0x0000000000000004  0x0000000000000000 
0x00007ffc8f5296e0:  0x0000000000000006  0x00007ffc8f529770 
0x00007ffc8f5296f0:  0x00007fe6ad614ce0  0x00007fe6ad53bdf5 
0x00007ffc8f529700:  0x0000000000000000  0x00007fe6ad53ff40 
0x00007ffc8f529710:  0x0000002a0000002a  0x00007fe6ad1a9bb4 
0x00007ffc8f529720:  0x0000000000000004  0x00000000029c9c00 
0x00007ffc8f529730:  0x0000000000000003  0x00007ffc8f529cf0 
0x00007ffc8f529740:  0x0000000000000000  0x00007fe6ad53bff1 
0x00007ffc8f529750:  0x0000003000000030  0x00007ffc8f529ce8 
0x00007ffc8f529760:  0x00007ffc8f529c10  0x00007ffc8f5297c8 
0x00007ffc8f529770:  0x00007fe6ad59479b  0x00007fe6ad58e762 
0x00007ffc8f529780:  0xffffffffffffffff  0x00007fe6ad5947a4 
0x00007ffc8f529790:  0x00007fe6ad242678  0xffffffffffffffff 
0x00007ffc8f5297a0:  0x00007fe6ad5947ae  0x00007fe6ad24699b 
0x00007ffc8f5297b0:  0xffffffffffffffff  0x00007fe6ad5947b8 
0x00007ffc8f5297c0:  0x00007fe6ad2487d0  0xffffffffffffffff 
runtime: unknown pc 0x7fe6ad5400f8
stack: frame={sp:0x7ffc8f5296d0, fp:0x0} stack=[0x7ffc8ed2ba10,0x7ffc8f52aa50)
0x00007ffc8f5295d0:  0x00007ffc8f5295e0  0x53e30870fee58e00 
0x00007ffc8f5295e0:  0x00000000029c9d2d  0x00000000029c9c00 
0x00007ffc8f5295f0:  0x00000000029c9c00  0x0000000003a36340 
0x00007ffc8f529600:  0x0000000000000001  0x0000000000000001 
0x00007ffc8f529610:  0x010004157f1c0300  0x170f12001a131100 
0x00007ffc8f529620:  0x0000000000000016  0x53e30870fee58e00 
0x00007ffc8f529630:  0x0000000000000000  0xffffffffffffff80 
0x00007ffc8f529640:  0x000000000000000b  0x0000000000000006 
0x00007ffc8f529650:  0x00007fe6aca34440  0x0000000000000006 
0x00007ffc8f529660:  0x00007fe6ad614d50  0x00007fe6ac8fe9e8 
0x00007ffc8f529670:  0x00007fe6aca35300  0x00007fe6ac8e7ba6 
0x00007ffc8f529680:  0x00007fe6aca34440  0x0000000000000006 
0x00007ffc8f529690:  0x0000000003a36340  0x00007fe6ad53febc 
0x00007ffc8f5296a0:  0x0000000000000044  0x00007ffc8f529770 
0x00007ffc8f5296b0:  0x0000000000000006  0x0000000000000000 
0x00007ffc8f5296c0:  0x00007fe6ad614ce0  0x00007fe6ad5400eb 
0x00007ffc8f5296d0: <0x0000000000000004  0x0000000000000000 
0x00007ffc8f5296e0:  0x0000000000000006  0x00007ffc8f529770 
0x00007ffc8f5296f0:  0x00007fe6ad614ce0  0x00007fe6ad53bdf5 
0x00007ffc8f529700:  0x0000000000000000  0x00007fe6ad53ff40 
0x00007ffc8f529710:  0x0000002a0000002a  0x00007fe6ad1a9bb4 
0x00007ffc8f529720:  0x0000000000000004  0x00000000029c9c00 
0x00007ffc8f529730:  0x0000000000000003  0x00007ffc8f529cf0 
0x00007ffc8f529740:  0x0000000000000000  0x00007fe6ad53bff1 
0x00007ffc8f529750:  0x0000003000000030  0x00007ffc8f529ce8 
0x00007ffc8f529760:  0x00007ffc8f529c10  0x00007ffc8f5297c8 
0x00007ffc8f529770:  0x00007fe6ad59479b  0x00007fe6ad58e762 
0x00007ffc8f529780:  0xffffffffffffffff  0x00007fe6ad5947a4 
0x00007ffc8f529790:  0x00007fe6ad242678  0xffffffffffffffff 
0x00007ffc8f5297a0:  0x00007fe6ad5947ae  0x00007fe6ad24699b 
0x00007ffc8f5297b0:  0xffffffffffffffff  0x00007fe6ad5947b8 
0x00007ffc8f5297c0:  0x00007fe6ad2487d0  0xffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x69ae50, 0xc0000a5e30)
        /usr/lib/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0000a5e08 sp=0xc0000a5dd0 pc=0x53481c
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x2a94290, 0x1, 0x2a9af30)
        _cgo_gotypes.go:3695 +0x4c fp=0xc0000a5e30 sp=0xc0000a5e08 pc=0x5dcb2c
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x2a9af30, 0x122e0, 0x6d1780)
        /home/sekai/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20210822212111-9ca8639aeefb/gio/v2/gapplication.go:901 +0x71 fp=0xc0000a5e78 sp=0xc0000a5e30 pc=0x5e3cb1
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc00000e048, {0xc000012200, 0x8205a7, 0x1})
        /home/sekai/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20210822212111-9ca8639aeefb/gio/v2/gapplication.go:901 +0x1be fp=0xc0000a5f40 sp=0xc0000a5e78 pc=0x5e3b9e
main.main()
        /home/sekai/Projects/mytest/main.go:15 +0xa5 fp=0xc0000a5f80 sp=0xc0000a5f40 pc=0x698b85
runtime.main()
        /usr/lib/go/src/runtime/proc.go:255 +0x227 fp=0xc0000a5fe0 sp=0xc0000a5f80 pc=0x5660a7
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000a5fe8 sp=0xc0000a5fe0 pc=0x58fe41

rax    0x0
rbx    0x1
rcx    0x3b1c136
rdx    0x3f
rdi    0x7
rsi    0x293d010
rbp    0x7ffc8f529770
rsp    0x7ffc8f5296d0
r8     0x3a36340
r9     0x7ffc8f5275e0
r10    0x7fe6ac9f83e0
r11    0x293
r12    0x6
r13    0x0
r14    0x7fe6ad614ce0
r15    0x7fe6ad614d50
rip    0x7fe6ad5400f8
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

It keeps appearing, but not in gtk3. What is going on?

**Comment by diamondburned** [comment]
It seems like this is a GTK4 error. Can you try running it on Wayland?

**Comment by diamondburned** [comment]
Closing this issue for now, since it doesn't have to do with gotk4 itself,
rather something to do with GTK4.
